{
  programs.plasma = {
    # hotkeys.commands = {
    #   brave = {
    #     comment = "Launch Brave browser.";
    #     key = "Meta+B";
    #     command = "brave";
    #   };
    # };
    shortcuts = {
      "kwin"."Window Close" = "Meta+Q";
      "kwin"."Kill Window" = "Meta+Shift+Q";
      "kwin"."Window Fullscreen" = "Meta+Shift+F";
      "kwin"."Window Maximize" = "Meta+F";
      "kwin"."Window Minimize" = "Meta+M";
      "kwin"."MoveMouseToCenter" = "Meta+C";
      "kwin"."MoveMouseToFocus" = "Meta+Shift+C";
      "kwin"."Overview" = "Meta+W";
      "kwin"."Show Desktop" = "Meta+D";
      "kwin"."Switch Window Left" = "Meta+J";
      "kwin"."Switch Window Down" = "Meta+K";
      "kwin"."Switch Window Up" = "Meta+L";
      "kwin"."Switch Window Right" = "Meta+;";
      "kwin"."Window Quick Tile Left" = "Meta+Left";
      "kwin"."Window Quick Tile Bottom" = "Meta+Down";
      "kwin"."Window Quick Tile Top" = "Meta+Up";
      "kwin"."Window Quick Tile Right" = "Meta+Right";
      "kwin"."Toggle Window Raise/Lower" = "Meta+T";
      "kwin"."Window On All Desktops" = "Meta+P";
      "kwin"."Walk Through Windows" = "Meta+Tab";
      "kwin"."Walk Through Windows (Reverse)" = "Meta+Shift+Tab";
      "kwin"."Switch to Desktop 1" = "Meta+1";
      "kwin"."Switch to Desktop 2" = "Meta+2";
      "kwin"."Switch to Desktop 3" = "Meta+3";
      "kwin"."Switch to Desktop 4" = "Meta+4";
      "kwin"."Switch to Desktop 5" = "Meta+5";
      "kwin"."Switch to Desktop 6" = "Meta+6";
      "kwin"."Switch to Desktop 7" = "Meta+7";
      "kwin"."Switch to Desktop 8" = "Meta+8";
      "kwin"."Switch to Desktop 9" = "Meta+9";
      "kwin"."Switch to Screen 0" = "Meta+Alt+1";
      "kwin"."Switch to Screen 1" = "Meta+Alt+2";
      "kwin"."Switch to Screen 2" = "Meta+Alt+3";
      "kwin"."Window to Desktop 1" = "Meta+Shift+1";
      "kwin"."Window to Desktop 2" = "Meta+Shift+2";
      "kwin"."Window to Desktop 3" = "Meta+Shift+3";
      "kwin"."Window to Desktop 4" = "Meta+Shift+4";
      "kwin"."Window to Desktop 5" = "Meta+Shift+5";
      "kwin"."Window to Desktop 6" = "Meta+Shift+6";
      "kwin"."Window to Desktop 7" = "Meta+Shift+7";
      "kwin"."Window to Desktop 8" = "Meta+Shift+8";
      "kwin"."Window to Desktop 9" = "Meta+Shift+9";
      "kwin"."Window to Screen 0" = "Meta+Ctrl+1";
      "kwin"."Window to Screen 1" = "Meta+Ctrl+2";
      "kwin"."Window to Screen 2" = "Meta+Ctrl+3";
      # "kwin"."Window Grow Horizontal" = "none,,Expand Window Horizontally";
      # "kwin"."Window Grow Vertical" = "none,,Expand Window Vertically";
      # "kwin"."Window Shrink Horizontal" = "none,,Shrink Window Horizontally";
      # "kwin"."Window Shrink Vertical" = "none,,Shrink Window Vertically";
      # "kwin"."Window Raise" = "none,,Raise Window";
      # "kwin"."Window Resize" = "none,,Resize Window";
      # "kwin"."Window Shade" = "none,,Shade Window";
      # "kwin"."Window to Next Desktop" = "none,,Window to Next Desktop";
      "kwin"."view_actual_size" = "Meta+0";
      "kwin"."view_zoom_in" = ["Meta++" "Meta+=,Meta++" "Meta+=,Zoom In"];
      "kwin"."view_zoom_out" = "Meta+-";
      # "plasmashell"."clear-history" = "none,,Clear Clipboard History";
      # "plasmashell"."clipboard_action" = "Meta+Ctrl+X";
      "services/org.kde.krunner.desktop"."_launch" = ["Meta+Space" "Search"];
      "services/org.kde.dolphin.desktop"."_launch" = "Meta+E";
    };
  };
}
